### ISSUE TITLE
Transformation for 'camera-pose-matrix' ?

### ISSUE THREAD

**Issue by nukbridge** [rameau-fr/MC-Calib#56]
### System information (version)

* Operating System / Platform => Ubuntu 22.04
* OpenCV => 4.5.5
* Ceres => 2.2.0
* Boost => 1.74.0
* C++ => 10.5.0
* Compiler => GNU GCC

### Vision system

* Number of cameras => 12
* Types of cameras => perspective (perspective, fisheye, hybrid)
* Multicamera configurations => converging (overlapping, non-overlapping, converging)
* Configuration file => 
[calib_configuration.zip](https://github.com/rameau-fr/MC-Calib/files/13679814/calib_configuration.zip)
 (i.e. `*.yml`)
* Image sequences => 100
    - number of images per camera
    - if relevant and possible, please share image sequences

### Describe the issue / bug

Please provide a clear and concise description of what the issue / bug is.

Hi, we're tried to use this toolbox for multi-view camera system based reconstruction, 
but we couldn't get proper results in our reconstruction pipeline (this pipeline were worked properly with our old style calibration data).
F.Y.I) 
- We made ChAruCo-Cube for multi-camera setup:
![ChAruCo-Cube](https://github.com/rameau-fr/MC-Calib/assets/585675/e4ffc97e-dffa-42b4-907c-ad21b9471859)

- calibration for old pipeline were done with 'camera-matrix' from MC-Calib and get extrinsic using old style 'Wand' approaches.

Actually we found 'camera-pose-matrix' values are not match to our old pipeline, but we're not sure any custom could be done in your MC-Calib sources. Here're comparison MC-Calib and our old pipeline data (just modified 'calibrated_cameras_data.yml' file in 'camera-pose-matrix' block):

- from MC-Calib: ![Plot_Result_ChAruCo](https://github.com/rameau-fr/MC-Calib/assets/585675/185bbb6d-ee60-4c49-8313-243644c216e3) 
- from our old calibration: ![Plot_Result_OLD_Wand](https://github.com/rameau-fr/MC-Calib/assets/585675/64861541-0f93-4df0-86c9-0b615da4bf85)

And check these original results with 'python_utils':
- from MC-Calib:  
[result_1.zip](https://github.com/rameau-fr/MC-Calib/files/13679898/result_1.zip)
- modified 'calibrated_cameras_data.yml' using our old calibration data: 
[result_2.zip](https://github.com/rameau-fr/MC-Calib/files/13679901/result_2.zip)

Could you give some advice for this problem ? (I think some transformation in 'camera-pose-matrix' can clear this issue but don't know where to start...)

Thanks,

**Comment by rameau-fr** [comment]
Thank you very much for using MC-Calib; from the plot you shared, it seems that MC-Calib did a great job at calibrating your system if the camera system is indeed a full-surrounding vision system. Did you get a satisfying reprojection error for this? Is the 3D object reconstruction consistent with your cube?

My first guess is simply that the poses should all be inverted for your reconstruction pipeline. Maybe you can try [modifying the line](https://github.com/rameau-fr/MC-Calib/blob/b862d3f68f15699b7661e5f498dd111dc5547d45/McCalib/src/McCalib.cpp#L386C9-L387C71) by removing the `.inv()` and recompiling the toolbox again. In this case, the display will become incompatible with this configuration, but it might work for your reconstruction pipeline.

Please let us know if this modification resolves your problem.

**Comment by rameau-fr** [comment]
Hello,

sorry for the delayed reply, I am just back to work. I think I figure out how to transform the MC-Calib extrinsic into your original format, I figured this out by experimenting with Matlab. Here is my code snippet:

```Matlab
% Poses mc_calib
P1_0 = [ 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1. ]
P1_1 = [ 9.3721409754506535e-01, -4.8487413819241591e-02, 3.4536749422015706e-01, -1.1615160240120219e+00, 4.7096107136164231e-02, 9.9881310030790837e-01, 1.2423660729542174e-02, -5.1198943311429670e-02, -3.4555996882655204e-01, 4.6218345302971794e-03, 9.3838528685725175e-01, 2.8873852221720903e-01, 0., 0., 0., 1. ]
P1_2 = [ 4.7959549131053109e-01, -2.5165862374442388e-01, 8.4062839698030223e-01, -2.5089514028069484e+00, 2.4081171318453279e-01, 9.5895834391790491e-01, 1.4969506813305264e-01, -3.3914593353855838e-01, -8.4379967024628555e-01, 1.3064008468035934e-01, 5.2051444241919742e-01, 1.1763415917803814e+00, 0., 0., 0., 1. ]
P1_0 = reshape(P1_0,4,4)'
P1_1 = reshape(P1_1,4,4)'
P1_2 = reshape(P1_2,4,4)'

% wand
P2_0 = [ 0.977376, -0.00253638, 0.211494, 0.18243, 0.107001, 0.868464, -0.484067, 1.59661, -0.182447, 0.495745, 0.849087, 6.56182, 0., 0., 0., 1. ]
P2_1 = [ 0.983759, -0.133839, -0.119605, -0.871716, 0.0586753, 0.869522, -0.490396, 1.60601, 0.169634, 0.475414, 0.863253, 6.38071, 0., 0., 0., 1. ]
P2_2 = [ 0.651279, -0.208894, -0.72952, -2.82728, -0.165888, 0.898918, -0.405497, 1.9035, 0.740485, 0.38511, 0.550793, 5.33995, 0., 0., 0., 1. ]
P2_0 = reshape(P2_0,4,4)'
P2_1 = reshape(P2_1,4,4)'
P2_2 = reshape(P2_2,4,4)'

% put in the same referencial
P1_0_Corrected = inv(P1_0)*P2_0
P1_1_Corrected = inv(P1_1)*P2_0
P1_2_Corrected = inv(P1_2)*P2_0

% error
P1_0_Corrected - P2_0
P1_1_Corrected - P2_1
P1_2_Corrected - P2_2
```

Basically, I used the pose of your first camera as refencial that I can call `Wand_ref` and I just to `inv(MC-Calib_pose)*Wand_ref`. It seems to work well on my similation.

I hope it helps!

**Comment by rameau-fr** [comment]
Sorry for the super delayed reply. 
What I provided can indeed work only if you know in what reference you want to express your camera setup, and for this, you need to find the most suitable solution for your own setup. 
By default, MC-Calib will assign it to the first camera, which is rather standard for robotic applications. If you cannot use Wand before, you need to find a way to know what referential it should be, but as I do not exactly know the requirements of your reconstruction software it is difficult for me to determine what would be the best. Maybe, we could have a look at Wand to see how they determine their main referential?

Regarding the invention of the poses, it is all a matter of convention, MC-Calib seems to output the inverse of Wand. It is like instead of providing M_{12} it returns the pose is M_{21}  (M being a 4x4 homogeneous transformation matrix).

**Comment by amy-tabb** [comment]
Hello, I have similar questions. I am evaluating MC-Calib relative to a known ground truth as well as my own calibration tool for a paper. If I use the camera pose values from `calibrated_cameras_data.yml`, the camera placement is very wrong. I know what the ground truth is with the first camera set at Identity. But the reprojection error is fine!

However, if I use the camera values output from the code, the result is fine. I tried to trace down where the output is coming from for the .yml file vs output and wasn't able to find it in a short amount of time. So, what does the camera pose data in `calibrated_cameras_data.yml` represent? The two options are not inverses of each other.

output snippet
```bash

 0004279 | 2024-07-18, 20:46:20.242298 [info] - Camera  0  :: [1, 0, 0, 0;
 0, 1, 0, 0;
 0, 0, 1, 0;
 0, 0, 0, 1]
0004280 | 2024-07-18, 20:46:20.242351 [info] - Camera  1  :: [0.9999951135164349, -0.0001112949582219276, 0.003124188964329618, 1000.410179129935;
 0.0001080763276775799, 0.9999994633190931, 0.001030379072601021, 0.1981208175771598;
 -0.003124301963632889, -0.001030036386800384, 0.9999945888665008, -3.32428833623438;
 0, 0, 0, 1]
0004281 | 2024-07-18, 20:46:20.242391 [info] - Camera  2  :: [-0.999998965942774, -9.309459452884154e-06, -0.001438063530092647, 3.598409578607149;
 -7.133527419208271e-06, 0.9999988552435407, -0.001513096401900568, 1.991183015526477;
 0.001438075969969733, -0.001513084578806678, -0.9999978212539076, 3001.185197790466;
 0, 0, 0, 1]
```



`calibrated_cameras_data.yml`
```yaml
%YAML:1.0
---
nb_camera: 8
camera_0:
   camera_matrix: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 1.3994458986602190e+03, 0., 5.9951321493512478e+02, 0.,
          1.4005562253930175e+03, 4.4836588130027894e+02, 0., 0., 1. ]
   distortion_vector: !!opencv-matrix
      rows: 1
      cols: 5
      dt: d
      data: [ 4.3899149163465802e-03, -1.2719962823535803e-02,
          -2.3817944165864017e-04, 2.2841988860744346e-04,
          2.6415608438885838e-02 ]
   distortion_type: 0
   camera_group: 0
   img_width: 1200
   img_height: 900
   camera_pose_matrix: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          1. ]
camera_1:
   camera_matrix: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 1.3998800245185396e+03, 0., 5.9519388696933640e+02, 0.,
          1.3999717438047014e+03, 4.4684311653164616e+02, 0., 0., 1. ]
   distortion_vector: !!opencv-matrix
      rows: 1
      cols: 5
      dt: d
      data: [ -2.2126764550145488e-02, 2.7799672650492296e-01,
          -5.4885485579900142e-04, -1.1051778894377200e-03,
          -8.6941744466936022e-01 ]
   distortion_type: 0
   camera_group: 0
   img_width: 1200
   img_height: 900
   camera_pose_matrix: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 9.9999511351643477e-01, 1.0807632767755120e-04,
          -3.1243019636328895e-03, -1.0004156981347836e+03,
          -1.1129495822195631e-04, 9.9999946331909306e-01,
          -1.0300363868003817e-03, -9.0204240104951233e-02,
          3.1241889643296174e-03, 1.0303790726010243e-03,
          9.9999458886650094e-01, 1.9859576708136489e-01, 0., 0., 0., 1. ]
```

[ground-truth-relative-cameras.txt](https://github.com/user-attachments/files/16312313/ground-truth-relative-cameras.txt)
